// Package collab.v1 carries a collaborative editing session.
//
// The service is deliberately thin. Because the document is a CRDT, the server
// never transforms an operation and never decides an outcome — it applies what
// it is sent to its own replica, hands it to everyone else, and can therefore be
// replaced, restarted, or run in several copies without any client noticing.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: collab.proto

package collabpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage is anything a participant sends.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Operations
	//	*ClientMessage_Presence
	Body          isClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_collab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_collab_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetBody() isClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetJoin() *Join {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetOperations() *Operations {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Operations); ok {
			return x.Operations
		}
	}
	return nil
}

func (x *ClientMessage) GetPresence() *Presence {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Join struct {
	Join *Join `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Operations struct {
	Operations *Operations `protobuf:"bytes,2,opt,name=operations,proto3,oneof"`
}

type ClientMessage_Presence struct {
	Presence *Presence `protobuf:"bytes,3,opt,name=presence,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Body() {}

func (*ClientMessage_Operations) isClientMessage_Body() {}

func (*ClientMessage_Presence) isClientMessage_Body() {}

// ServerMessage is anything the server sends back.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_Operations
	//	*ServerMessage_Presence
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_collab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_collab_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetOperations() *Operations {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Operations); ok {
			return x.Operations
		}
	}
	return nil
}

func (x *ServerMessage) GetPresence() *Presence {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_Operations struct {
	Operations *Operations `protobuf:"bytes,2,opt,name=operations,proto3,oneof"`
}

type ServerMessage_Presence struct {
	Presence *Presence `protobuf:"bytes,3,opt,name=presence,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Body() {}

func (*ServerMessage_Operations) isServerMessage_Body() {}

func (*ServerMessage_Presence) isServerMessage_Body() {}

// Join opens a session. It must be the first message, and it must not be sent
// twice.
type Join struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// document names the document to edit. It is opened if it does not exist.
	Document string `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// site is the participant's replica identity, which must be distinct from
	// every other participant's. See crdt.DeriveSiteID.
	Site uint64 `protobuf:"varint,2,opt,name=site,proto3" json:"site,omitempty"`
	// have is the participant's encoded version vector, sent when rejoining a
	// document it already holds. The server then replies with only the operations
	// that are missing, instead of the whole document. Empty means "send
	// everything".
	Have          []byte `protobuf:"bytes,3,opt,name=have,proto3" json:"have,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_collab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_collab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_collab_proto_rawDescGZIP(), []int{2}
}

func (x *Join) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *Join) GetSite() uint64 {
	if x != nil {
		return x.Site
	}
	return 0
}

func (x *Join) GetHave() []byte {
	if x != nil {
		return x.Have
	}
	return nil
}

// Welcome answers a Join with the state of the document at that moment.
type Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// snapshot is the whole document, sent when the participant is new to it or
	// too far behind to catch up cheaply. Empty when operations were sent instead.
	Snapshot []byte `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// operations catches up a participant that supplied a version vector.
	Operations []byte `protobuf:"bytes,2,opt,name=operations,proto3" json:"operations,omitempty"`
	// presence is the state of everyone already in the document.
	Presence [][]byte `protobuf:"bytes,3,rep,name=presence,proto3" json:"presence,omitempty"`
	// version is the server's encoded version vector. A participant answers with
	// whatever the server is missing, which is what lets work done while
	// disconnected reach everyone else rather than being stranded.
	Version       []byte `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_collab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_collab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_collab_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Welcome) GetOperations() []byte {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Welcome) GetPresence() [][]byte {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *Welcome) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

// Operations carries a batch of CRDT operations, encoded by crdt.AppendOps.
// Applying them is idempotent and order-independent, so this message needs no
// sequencing of its own.
type Operations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []byte                 `protobuf:"bytes,1,opt,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operations) Reset() {
	*x = Operations{}
	mi := &file_collab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operations) ProtoMessage() {}

func (x *Operations) ProtoReflect() protoreflect.Message {
	mi := &file_collab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operations.ProtoReflect.Descriptor instead.
func (*Operations) Descriptor() ([]byte, []int) {
	return file_collab_proto_rawDescGZIP(), []int{4}
}

func (x *Operations) GetOperations() []byte {
	if x != nil {
		return x.Operations
	}
	return nil
}

// Presence carries one encoded awareness update: a cursor, a selection, or a
// departure. It is never persisted.
type Presence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        []byte                 `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_collab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_collab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_collab_proto_rawDescGZIP(), []int{5}
}

func (x *Presence) GetUpdate() []byte {
	if x != nil {
		return x.Update
	}
	return nil
}

var File_collab_proto protoreflect.FileDescriptor

const file_collab_proto_rawDesc = "" +
	"\n" +
	"\fcollab.proto\x12\tcollab.v1\"\xaa\x01\n" +
	"\rClientMessage\x12%\n" +
	"\x04join\x18\x01 \x01(\v2\x0f.collab.v1.JoinH\x00R\x04join\x127\n" +
	"\n" +
	"operations\x18\x02 \x01(\v2\x15.collab.v1.OperationsH\x00R\n" +
	"operations\x121\n" +
	"\bpresence\x18\x03 \x01(\v2\x13.collab.v1.PresenceH\x00R\bpresenceB\x06\n" +
	"\x04body\"\xb3\x01\n" +
	"\rServerMessage\x12.\n" +
	"\awelcome\x18\x01 \x01(\v2\x12.collab.v1.WelcomeH\x00R\awelcome\x127\n" +
	"\n" +
	"operations\x18\x02 \x01(\v2\x15.collab.v1.OperationsH\x00R\n" +
	"operations\x121\n" +
	"\bpresence\x18\x03 \x01(\v2\x13.collab.v1.PresenceH\x00R\bpresenceB\x06\n" +
	"\x04body\"J\n" +
	"\x04Join\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\x12\x12\n" +
	"\x04site\x18\x02 \x01(\x04R\x04site\x12\x12\n" +
	"\x04have\x18\x03 \x01(\fR\x04have\"{\n" +
	"\aWelcome\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\x12\x1e\n" +
	"\n" +
	"operations\x18\x02 \x01(\fR\n" +
	"operations\x12\x1a\n" +
	"\bpresence\x18\x03 \x03(\fR\bpresence\x12\x18\n" +
	"\aversion\x18\x04 \x01(\fR\aversion\",\n" +
	"\n" +
	"Operations\x12\x1e\n" +
	"\n" +
	"operations\x18\x01 \x01(\fR\n" +
	"operations\"\"\n" +
	"\bPresence\x12\x16\n" +
	"\x06update\x18\x01 \x01(\fR\x06update2K\n" +
	"\x06Collab\x12A\n" +
	"\aSession\x12\x18.collab.v1.ClientMessage\x1a\x18.collab.v1.ServerMessage(\x010\x01B$Z\"github.com/go-crdt/collab/collabpbb\x06proto3"

var (
	file_collab_proto_rawDescOnce sync.Once
	file_collab_proto_rawDescData []byte
)

func file_collab_proto_rawDescGZIP() []byte {
	file_collab_proto_rawDescOnce.Do(func() {
		file_collab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collab_proto_rawDesc), len(file_collab_proto_rawDesc)))
	})
	return file_collab_proto_rawDescData
}

var file_collab_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_collab_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: collab.v1.ClientMessage
	(*ServerMessage)(nil), // 1: collab.v1.ServerMessage
	(*Join)(nil),          // 2: collab.v1.Join
	(*Welcome)(nil),       // 3: collab.v1.Welcome
	(*Operations)(nil),    // 4: collab.v1.Operations
	(*Presence)(nil),      // 5: collab.v1.Presence
}
var file_collab_proto_depIdxs = []int32{
	2, // 0: collab.v1.ClientMessage.join:type_name -> collab.v1.Join
	4, // 1: collab.v1.ClientMessage.operations:type_name -> collab.v1.Operations
	5, // 2: collab.v1.ClientMessage.presence:type_name -> collab.v1.Presence
	3, // 3: collab.v1.ServerMessage.welcome:type_name -> collab.v1.Welcome
	4, // 4: collab.v1.ServerMessage.operations:type_name -> collab.v1.Operations
	5, // 5: collab.v1.ServerMessage.presence:type_name -> collab.v1.Presence
	0, // 6: collab.v1.Collab.Session:input_type -> collab.v1.ClientMessage
	1, // 7: collab.v1.Collab.Session:output_type -> collab.v1.ServerMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_collab_proto_init() }
func file_collab_proto_init() {
	if File_collab_proto != nil {
		return
	}
	file_collab_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Operations)(nil),
		(*ClientMessage_Presence)(nil),
	}
	file_collab_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_Operations)(nil),
		(*ServerMessage_Presence)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collab_proto_rawDesc), len(file_collab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collab_proto_goTypes,
		DependencyIndexes: file_collab_proto_depIdxs,
		MessageInfos:      file_collab_proto_msgTypes,
	}.Build()
	File_collab_proto = out.File
	file_collab_proto_goTypes = nil
	file_collab_proto_depIdxs = nil
}
