// Package collab.v1 carries a collaborative editing session.
//
// The service is deliberately thin. Because the document is a CRDT, the server
// never transforms an operation and never decides an outcome — it applies what
// it is sent to its own replica, hands it to everyone else, and can therefore be
// replaced, restarted, or run in several copies without any client noticing.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: collab.proto

package collabpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Collab_Session_FullMethodName = "/collab.v1.Collab/Session"
)

// CollabClient is the client API for Collab service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Collab is one bidirectional stream per participant per document.
type CollabClient interface {
	// Session carries a participant's whole involvement with one document: it
	// opens with a Join, and from then on operations and presence flow both ways
	// until either side hangs up.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type collabClient struct {
	cc grpc.ClientConnInterface
}

func NewCollabClient(cc grpc.ClientConnInterface) CollabClient {
	return &collabClient{cc}
}

func (c *collabClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Collab_ServiceDesc.Streams[0], Collab_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Collab_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// CollabServer is the server API for Collab service.
// All implementations must embed UnimplementedCollabServer
// for forward compatibility.
//
// Collab is one bidirectional stream per participant per document.
type CollabServer interface {
	// Session carries a participant's whole involvement with one document: it
	// opens with a Join, and from then on operations and presence flow both ways
	// until either side hangs up.
	Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedCollabServer()
}

// UnimplementedCollabServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollabServer struct{}

func (UnimplementedCollabServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedCollabServer) mustEmbedUnimplementedCollabServer() {}
func (UnimplementedCollabServer) testEmbeddedByValue()                {}

// UnsafeCollabServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollabServer will
// result in compilation errors.
type UnsafeCollabServer interface {
	mustEmbedUnimplementedCollabServer()
}

func RegisterCollabServer(s grpc.ServiceRegistrar, srv CollabServer) {
	// If the following call panics, it indicates UnimplementedCollabServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Collab_ServiceDesc, srv)
}

func _Collab_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollabServer).Session(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Collab_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// Collab_ServiceDesc is the grpc.ServiceDesc for Collab service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collab_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collab.v1.Collab",
	HandlerType: (*CollabServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Collab_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "collab.proto",
}
